---
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
  - |
    [plugins."io.containerd.grpc.v1.cri".registry]
      config_path = "/etc/containerd/certs.d"
kind: Cluster
name: iron-1
nodes:
  - extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    role: control-plane
  - extraMounts:
      - containerPath: /data
        hostPath: /Users/marc/make/data
      - containerPath: /build
        hostPath: /Users/marc/make/build
    extraPortMappings:
      - containerPort: 30017
        hostPort: 30017
        protocol: TCP
    role: worker
